#!/bin/bash
# #588 — codex-gate must fire on git commit in COMMAND POSITION, and not on a
# command that merely mentions the verb.
#
# Why this suite exists separately from tests/test-hooks.sh: want values here are
# GENERATED BY AN ORACLE wherever the oracle can run, rather than hand-asserted.
# A bash oracle puts a fake `git` on PATH that logs whenever it is invoked with
# `commit`, runs the real shape through `bash -c`, and reports whether git was
# actually invoked. That is ground truth for what the shell does; the gate's job
# is to agree with it.
#
# FIVE ROWS ARE NOT ORACLE-GENERATED on this box, and saying otherwise would
# break this repo's own claim rule (Sol caught an earlier version of this
# comment doing exactly that). They are `declared`, and each prints its reason
# when it runs:
#
#   timeout 5 git commit     `timeout` is not installed on macOS
#   timeout 5s git commit    same
#   stdbuf -oL git commit    `stdbuf` is not installed on macOS
#   sudo git commit          sudo cannot run unattended in a fixture
#   /usr/bin/git commit      an absolute path bypasses the PATH interposition
#                            the oracle works by, so it is declared on EVERY
#                            platform, not just this one
#
# `timeout` and `stdbuf` are named by bare name, so they measure for real on any
# box that has them — including the Linux CI runner, where the count drops to
# two. `sudo` and `/usr/bin/git` carry the `!` marker and are declared on EVERY
# platform. Everything else in the suite is measured here. The count above is
# what THIS suite printed on macOS, not a recollection: grep the run for
# `declared (`.
#
# This method is not decoration. The first hand-written want column for these
# shapes had 2 of 9 rows wrong, and BOTH errors under-counted the regression:
#
#   - `timeout 5 git commit` looked inert only because `timeout` is not
#     installed on macOS. It exists on the Linux CI runner and on consumer
#     machines.
#   - `xargs git commit < /dev/null` looked inert only because BSD xargs does
#     not run the command on empty input. GNU xargs does, and consumers run
#     Linux.
#
# Both are handled below rather than papered over: a shape whose wrapper is
# absent on this box is reported ORACLE-UNAVAILABLE and asserted against a
# declared expectation with its reason, so the row never silently degrades into
# a vacuous pass.
#
# The gate is an accident-catcher, not an adversary barrier — its own header
# says so, and #588 concedes deliberate bypass is trivial. So the wrapper set is
# CLOSED and enumerated. Wrappers outside it (doas, setsid, caffeinate,
# unbuffer, flock, ...) are a known, accepted false NEGATIVE, recorded on #588.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"


PASS=0
FAIL=0
pass() { echo "  PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); }

WORK=$(mktemp -d) || { echo "FATAL: could not create temp dir" >&2; exit 1; }
case "$WORK" in
    /*) ;;
    *) echo "FATAL: mktemp returned a non-absolute path ('$WORK') — refusing to run" >&2; exit 1 ;;
esac
trap 'rm -rf "$WORK"' EXIT

# ---------------------------------------------------------------- the oracle
#
# A fake `git` that records an invocation when ANY argument is exactly `commit`
# — it does not parse the subcommand chain, and claiming it did would break this
# repo's own claim rule. That is deliberately coarse: this oracle answers "did
# the shell run git with the verb in its argv", which is the question the gate
# is deciding, not "what would git have done". It never touches a real
# repository, so a row that genuinely invokes git cannot create a commit.
mkdir -p "$WORK/bin"
cat > "$WORK/bin/git" <<'ORACLE_GIT'
#!/bin/bash
for a in "$@"; do
    if [ "$a" = "commit" ]; then
        echo INVOKED >> "$ORACLE_LOG"
        exit 0
    fi
done
exit 0
ORACLE_GIT
chmod +x "$WORK/bin/git"

# Runs a shape and reports what the SHELL does with it: INVOKES or inert.
oracle() {
    ORACLE_LOG="$WORK/oracle.log"
    export ORACLE_LOG
    : > "$ORACLE_LOG"
    # The trailing `wait` is load-bearing for backgrounding shapes: `coproc git
    # commit` genuinely invokes, but the coprocess runs asynchronously and
    # `bash -c` exits before it writes the log. Without the wait the oracle
    # reports `inert` for a shape that really runs git — a false ALLOW want.
    ( cd "$WORK" && PATH="$WORK/bin:$PATH" bash -c "$1"$'\n''wait' ) > /dev/null 2>&1
    if [ -s "$ORACLE_LOG" ]; then echo INVOKES; else echo inert; fi
}

# Runs a shape through the gate's TEXT layer only, on a root with no
# .reviews/handoff.json. Probing inside the working repo is confounded: the
# in-flight PENDING_RECHECK lane allows real commits, so `git commit -m x`
# reports ALLOW there for reasons that have nothing to do with #588.
mkdir -p "$WORK/clean/hooks"
cp "$REPO_ROOT/hooks/codex-gate-check.sh" "$REPO_ROOT/hooks/_find-sdlc-root.sh" "$WORK/clean/hooks/"
gate() {
    local json
    json=$(python3 -c 'import json,sys; print(json.dumps({"tool_name":"Bash","tool_input":{"command":sys.argv[1],"description":"fixture"}}))' "$1")
    if printf '%s' "$json" | ( cd "$WORK/clean" && ./hooks/codex-gate-check.sh ) > /dev/null 2>&1; then
        echo ALLOW
    else
        echo BLOCK
    fi
}

# Fixture state the rows depend on. Without these the oracle reports `inert` for
# a shape that genuinely invokes — a false PASS waiting to happen, and exactly
# what the oracle/declared cross-check below is here to catch.
mkdir -p "$WORK/sub"          # so `cd sub && ...` does not short-circuit on &&
cp "$WORK/bin/git" "$WORK/git" # so `./git commit` resolves to the fake

# A row the oracle cannot measure here. Two causes, both real:
#   - the named wrapper is not installed on this box
#   - the shape names an ABSOLUTE path to git, which by construction bypasses
#     the PATH interposition the oracle works by
# Either way the row falls back to its declared value WITH its reason printed,
# so an unmeasurable row can never quietly read as `inert`.
oracle_can_measure() {
    case "$1" in
        "")  return 0 ;;
        "!"*) return 1 ;;
        *)   command -v "$1" > /dev/null 2>&1 ;;
    esac
}

# ------------------------------------------------------------------ the table
#
# Fields: wrapper-binary-needed | declared | reason | command
#   declared      what the shape does in a POSIX shell where every named binary
#                 exists. Used ONLY when the oracle cannot run here.
# The oracle overrides `declared` whenever it can run. A disagreement between
# the two is itself reported, because it means one of them is wrong.
run_row() {
    local needs="$1" declared="$2" reason="$3" cmd="$4"
    local truth source g want

    if oracle_can_measure "$needs"; then
        truth=$(oracle "$cmd")
        source="oracle"
        if [ "$truth" != "$declared" ]; then
            fail "oracle/declared disagree for [$cmd]: oracle says $truth, table declares $declared — one of them is wrong"
            return
        fi
    else
        truth="$declared"
        source="declared (${needs#!} unmeasurable here: $reason)"
    fi

    if [ "$truth" = "INVOKES" ]; then want=BLOCK; else want=ALLOW; fi
    g=$(gate "$cmd")

    if [ "$g" = "$want" ]; then
        pass "[$source: $truth] gate $g — $cmd"
    else
        fail "[$source: $truth] gate $g, want $want — $cmd"
    fi
}

echo "=== #588: gate agrees with the shell about what invokes git commit ==="

echo "--- real invocations (oracle: INVOKES, want BLOCK) ---"
run_row ""        INVOKES "" 'git commit -m x'
run_row ""        INVOKES "" 'cd sub && git commit -m x'
run_row ""        INVOKES "" '(cd sub; git commit -m x)'
run_row ""        INVOKES "" 'git -C /tmp/r commit -m x'
run_row ""        INVOKES "" 'git -c user.name="A B" commit -m x'

echo "--- enumerated wrapper prefixes (oracle: INVOKES, want BLOCK) ---"
run_row "env"     INVOKES "" 'env X=1 git commit -m x'
run_row "command" INVOKES "" 'command git commit -m x'
run_row "nice"    INVOKES "" 'nice git commit -m x'
run_row "nohup"   INVOKES "" 'nohup git commit -m x'
# WITH input, deliberately. `xargs git commit < /dev/null` invokes on GNU and
# not on BSD; the fed form invokes on both, so the row means the same thing on
# the dev box and the CI runner.
run_row "xargs"   INVOKES "" 'echo -m x | xargs git commit'
run_row "timeout" INVOKES "not installed on macOS; present on the Linux runner and on consumer machines" 'timeout 5 git commit -m x'

echo "--- eval/exec/time and escaped git (oracle: INVOKES, want BLOCK) ---"
# Every row here was found by hunting fail-opens with the oracle BEFORE review,
# and every one shipped blocked on origin/main. Anchoring alone would have let
# them through — the regression these rows exist to prevent.
run_row ""        INVOKES "" 'eval git commit -m x'
run_row ""        INVOKES "" 'exec git commit -m x'
run_row ""        INVOKES "" 'time git commit -m x'
# `\git` runs git — the escape only suppresses alias expansion.
run_row ""        INVOKES "" '\git commit -m x'
# `builtin` is deliberately NOT transparent: it only runs shell builtins, and
# git is not one, so the shape is inert and allowing it is correct. origin/main
# denied it; that false positive is fixed here.
run_row ""        inert   "" 'builtin git commit -m x'

echo "--- reserved words and redirections (Sol round 1, all fail-open) ---"
# Every row here shipped BLOCKED on origin/main and walked past the first cut of
# the command-position anchor. bash begins a command after these reserved words
# exactly as it does after then/do/else, and it permits redirections before the
# command word.
run_row ""        INVOKES "" 'if git commit -m x; then :; fi'
run_row ""        INVOKES "" 'while git commit -m x; do break; done'
run_row ""        INVOKES "" 'until git commit -m x; do break; done'
run_row ""        INVOKES "" '</dev/null git commit -m x'
run_row ""        INVOKES "" '2>/dev/null git commit -m x'
run_row ""        INVOKES "" 'FOO=1 </dev/null git commit -m x'

echo "--- wrapper options that take an argument (Sol round 1, all fail-open) ---"
# The first cut allowed only flags and bare numbers after a wrapper, so an
# option with an argument broke the chain. Enumerating each wrapper's real
# option grammar is not winnable, so the tokens between an enumerated wrapper
# and `git` are skipped wholesale, stopping at `;`, `&` or `|`.
run_row "env"     INVOKES "" 'env -u FOO git commit -m x'
run_row "xargs"   INVOKES "" "printf 'x\n' | xargs -I X git commit -m X"
run_row "timeout" INVOKES "not installed on macOS; present on the Linux runner and on consumer machines" 'timeout 5s git commit -m x'

echo "--- assignment prefixes (oracle: INVOKES, want BLOCK) ---"
# bash runs an assignment-prefixed command directly — there is no wrapper here
# at all. This repo's own workflow uses the shape (AFTERHOURS_SKIP=1 git push).
run_row ""        INVOKES "" 'FOO=1 git commit -m x'
run_row ""        INVOKES "" 'GIT_AUTHOR_NAME="A B" git commit -m x'

echo "--- path-prefixed git (oracle: INVOKES, want BLOCK) ---"
run_row "!absolute path" INVOKES "an absolute path bypasses the PATH interposition the oracle works by" '/usr/bin/git commit -m x'
run_row ""        INVOKES "" './git commit -m x'

echo "--- path-prefixed WRAPPERS (oracle: INVOKES, want BLOCK) ---"
# The `(\S*/)?` prefix went on `git` in the first cut but not on the wrapper
# alternation, so a wrapper named by path escaped while its bare name was
# caught. `/usr/bin/env` is a shape people type without thinking about it.
run_row ""        INVOKES "" '/usr/bin/env git commit -m x'
run_row ""        INVOKES "" '/usr/bin/nice git commit -m x'
run_row ""        INVOKES "" '/usr/bin/env -u FOO git commit -m x'

echo "--- backslash-escaped word content (Sol round 2, all fail-open) ---"
# A backslash makes the next character ordinary word content. Modelling a word
# as "runs to the next space or separator" splits each of these early and lets
# the invocation through. All four block on origin/main.
run_row ""        INVOKES "" 'FOO=a\ b git commit -m x'
run_row ""        INVOKES "" 'env FOO=a\;b git commit -m x'
run_row ""        INVOKES "" 'env FOO=a\&b git commit -m x'
run_row ""        INVOKES "" 'env FOO=a\|b git commit -m x'

echo "--- Sol round 13: operators missing from the redirection set ---"
# The SEVENTH narrowing instance, and the first outside GATE_ASSIGN. The
# operator enumeration omitted `<<`, `<<-` and `<>`. An ATTACHED operand still
# matched by accident through a shorter operator; a SEPARATED one escaped.
run_row ""        INVOKES "" '<< EOF git commit -m x
body
EOF'
run_row ""        INVOKES "" '<<- EOF git commit -m x
body
EOF'
run_row ""        INVOKES "" '<> /dev/null git commit -m x'

echo "--- Sol round 13: the double-quote masker was not escape-aware ---"
# The EIGHTH instance. The masker assumed a double-quoted span contains no
# backslash, so a Windows path or an escaped char left the span unmasked and the
# whitespace inside it broke the assignment and git-option chains downstream.
run_row ""        INVOKES "" 'FOO="C:\Program Files" git commit -m x'
run_row ""        INVOKES "" 'git -c user.name="A\B C" commit -m x'
# The escape alternative must NOT swallow the closing quote. `\.` does, and
# under POSIX longest-match this whole command masks to `cd Q` — the invocation
# vanishes. That was the reviewer's own suggested fix, and test-hooks.sh caught
# it in the same commit that applied it. Pinned here so it cannot come back.
# These need a quoted span on BOTH sides of the invocation, or the row does not
# pin the over-mask at all. Sol mutation-tested an earlier version of these rows
# against the rejected `\.` expression and this suite stayed GREEN — the claim
# that they pinned it was false. Verified by mutation this time, not by reading.
run_row ""        INVOKES "" 'cd "sub" && git commit -m "message"'
run_row ""        INVOKES "" 'git -c user.name="A B" commit -m "fix"'
run_row ""        INVOKES "" 'cd sub && git commit -m "message"'
run_row ""        INVOKES "" 'git -c user.name="A B" commit -m x'

echo "--- Sol round 14: escaped quotes inside a quoted span (10th and 11th) ---"
# The masker handled a backslash before a NON-quote but not an escaped quote,
# so it paired the wrong quotes and left whitespace that broke the prefix chain.
run_row ""        INVOKES "" 'FOO="a b\" c" git commit -m x'
run_row ""        INVOKES "" 'git -c user.name="A B\" C" commit -m x'
run_row ""        INVOKES "" '> "a b\" c" git commit -m x'
# shellcheck disable=SC1003  # (applies to the three rows below) the backslash
# before the apostrophe is the SHAPE UNDER TEST, not a quoting mistake.
# The single-quote masker had the analogous hole. `'"'"'a b'"'"'\'"'"''"'"'c d'"'"'` is the ordinary
# shell idiom for an apostrophe inside single quotes.
run_row ""        INVOKES "" 'FOO='"'"'a b'"'"'\'"'"''"'"'c d'"'"' git commit -m x'
# shellcheck disable=SC1003
run_row ""        INVOKES "" 'git -c user.name='"'"'A B'"'"'\'"'"''"'"' C'"'"' commit -m x'
# PARITY CANARY: neutralising every `\'"'"'` would break an EVEN backslash run,
# where the apostrophe is a real quote. Pairs are set aside first, and the
# restore must emit the PAIR — restoring one backslash collapsed the run and
# broke k=5 and k=13 in the backslash contract below.
# shellcheck disable=SC1003
run_row ""        INVOKES "" 'FOO=\\'"'"'a b'"'"' git commit -m x'

echo "--- redirection operand separated from its operator (Sol round 2) ---"
# `< /dev/null git commit` is an ordinary invocation; the space after the
# operator is legal and GATE_REDIR used to require the operand to touch it.
run_row ""        INVOKES "" '< /dev/null git commit -m x'
run_row ""        INVOKES "" '2> /dev/null git commit -m x'

echo "--- remaining enumerated wrappers and reserved words, pinned (Sol round 2) ---"
# Named in the hook's comment as covered, so they are pinned here rather than
# left as an untested claim. sudo is unmeasurable: it prompts or refuses.
run_row "!sudo"   INVOKES "sudo cannot run unattended in a test fixture" 'sudo git commit -m x'
run_row "stdbuf"  INVOKES "not installed on macOS; present on the Linux runner" 'stdbuf -oL git commit -m x'
run_row ""        INVOKES "" 'if false; then :; elif git commit -m x; then :; fi'

echo "--- Sol round 4 fail-opens (>|, stacked builtin, git option operands) ---"
run_row ""        INVOKES "" '>|/dev/null git commit -m x'
run_row ""        INVOKES "" '2>| /dev/null git commit -m x'
run_row ""        INVOKES "" 'builtin builtin command git commit -m x'
# Pre-existing on origin/main rather than an anchor regression, but it made the
# hook's own "every site uses the word atom" comment false, so it is fixed here.
run_row ""        INVOKES "" 'git -c user.name=A\ b commit -m x'

echo "--- Sol round 4 false positives (oracle: inert, want ALLOW) ---"
# `builtin` runs only shell builtins, so neither of these reaches git. The
# assignment grammar accepted any non-space left side; bash does not — it runs
# `A-B=1` and `1A=1` as commands, so treating them as prefixes was wrong.
run_row ""        inert "" 'builtin env git commit -m x'
run_row ""        inert "" 'builtin /usr/bin/command git commit -m x'
run_row ""        inert "" 'A-B=1 git commit -m x'
run_row ""        inert "" '1A=1 git commit -m x'

echo "--- Sol round 5 fail-opens (+=, separated --git-dir, builtin spellings) ---"
run_row ""        INVOKES "" 'FOO+=1 git commit -m x'
run_row ""        INVOKES "" 'git --git-dir .git commit -m x'
run_row ""        INVOKES "" 'builtin -- command git commit -m x'
run_row ""        INVOKES "" '\builtin command git commit -m x'
run_row ""        INVOKES "" 'builtin \command git commit -m x'

echo "--- Sol round 9: array-element assignment prefixes (all fail-open) ---"
# An array-element assignment is a command prefix exactly as a scalar one is.
# Narrowing GATE_ASSIGN to scalar names in round 4 — to kill the `A-B=1` false
# positives — excluded these and opened a fail-open. BLOCK on origin/main,
# ALLOW from 27bf763 until this fix.
run_row ""        INVOKES "" 'A[0]=x git commit -m x'
run_row ""        INVOKES "" 'A[foo]=x git commit -m x'
run_row ""        INVOKES "" 'A[0]+=x git commit -m x'
# A subscript is an ARITHMETIC EXPRESSION, not an identifier: it nests, and it
# may be empty (`A[]` is index 0). A first cut bounded it to a nonempty,
# non-nested span and left all four of these fail-open — the third time in this
# review that tightening a grammar against a false positive left a fail-open in
# the same expression.
run_row ""        INVOKES "" 'A[]=x git commit -m x'
run_row ""        INVOKES "" 'A[B[0]]=x git commit -m x'
run_row ""        INVOKES "" 'A[B[0]]+=x git commit -m x'
run_row ""        INVOKES "" 'A[1+A[0]]=x git commit -m x'
# A subscript is ARITHMETIC, so `=` is valid inside it too. Bounding the span to
# "anything but =" (round 10's fix) closed the nesting hole and opened this one —
# the two cuts were exact mirrors, and the fourth instance of the pattern.
run_row ""        INVOKES "" 'A[B=1]=x git commit -m x'
run_row ""        INVOKES "" 'A[1==1]=x git commit -m x'
run_row ""        INVOKES "" 'A[B+=1]=x git commit -m x'
run_row ""        INVOKES "" 'A[B<=1]=x git commit -m x'
run_row ""        INVOKES "" 'A[B[0]=1]=x git commit -m x'
run_row ""        INVOKES "" 'declare -A A; A[x=y]=z git commit -m x'
# A quoted key containing a space arrives already masked to `A[Q]=x`.
run_row ""        INVOKES "" 'A["foo bar"]=x git commit -m x'
# Bash's assignment lexer KEEPS whitespace inside an arithmetic subscript — the
# word does not split. Bounding the span by whitespace on the opposite reasoning
# was the sixth instance of the narrowing pattern, and these are why the span is
# now unbounded — there is no whitespace bound any more.
run_row ""        INVOKES "" 'A[1 + 2]=x git commit -m x'
run_row ""        INVOKES "" 'A[1\ +\ 2]=x git commit -m x'
run_row ""        INVOKES "" 'A[1\ +\ 2]+=x git commit -m x'
run_row ""        INVOKES "" 'declare -A A; A[foo\ bar]=x git commit -m x'
# shellcheck disable=SC2016  # must reach the gate unexpanded — expanding it
# here would test the arithmetic result, not the subscript text.
run_row ""        INVOKES "" 'A[$((1 + 2))]=x git commit -m x'
# CANARY: the round-4 false-positive class must not come back with it. A
# malformed name is still not an assignment, subscript or no subscript. This
# row also BLOCKS against the pre-round-4 `[^ =]*=` grammar, so it fails if the
# old malformed-name grammar returns — it proves NAME protection, which is what
# actually carries the safety here, rather than the subscript bound.
run_row ""        inert "" 'A[0]-B=1 git commit -m x'
# DECLARED FAIL-CLOSED. The whitespace bound does not validate bracket balance —
# POSIX ERE cannot without a bounded nesting limit or the scanner #533 ruled out.
# So this unbalanced span, which is not an assignment at all, is read as one and
# blocked. Pinned as a row rather than described, because two earlier versions of
# the hook comment claimed a safety they were not providing.
# Asserted in the opposite direction from the rows around it — it is a false
# POSITIVE, so run_row (which wants inert => ALLOW) does not fit.
# The unbounded span is greedy across a real command boundary too: it fuses two
# balanced array-looking fragments either side of a `;` into one fictional
# assignment. Materially different from merely tolerating unbalanced brackets,
# so it is pinned separately rather than folded into the row below.
xcmd='A[0]=x; echo A[1]=y git commit -m x'
truth=$(oracle "$xcmd"); g=$(gate "$xcmd")
if [ "$truth" = "inert" ] && [ "$g" = "BLOCK" ]; then
    pass "ACCEPTED LIMIT still holds (inert, blocked — the unbounded span reaches across a ';') — $xcmd"
else
    fail "ACCEPTED LIMIT changed [oracle=$truth gate=$g] — $xcmd"
fi

ubs='A[0]-B[1]=x git commit -m x'
truth=$(oracle "$ubs"); g=$(gate "$ubs")
if [ "$truth" = "inert" ] && [ "$g" = "BLOCK" ]; then
    pass "ACCEPTED LIMIT still holds (inert, blocked — unbalanced bracket span; ERE cannot validate balance) — $ubs"
else
    fail "ACCEPTED LIMIT changed [oracle=$truth gate=$g] — $ubs"
fi
# LATENT DEPENDENCY, pinned for #603: this blocks only through the unconditional
# `)` anchor, NOT because GATE_ASSIGN consumes a compound value. #603 narrows
# the punctuation anchors; without this row that change silently re-opens it.
run_row ""        INVOKES "" 'A=(x y) git commit -m x'
run_row ""        INVOKES "" 'A+=(x y) git commit -m x'

echo "--- Sol round 5 false positives (oracle: inert, want ALLOW) ---"
# A reserved word is only a command-position marker when the reserved word is
# ITSELF at a boundary. In `echo if git commit` the `if` is an argument.
run_row ""        inert "" 'echo if git commit'
run_row ""        inert "" 'echo then git commit'
run_row ""        inert "" 'echo do git commit'
run_row ""        inert "" 'echo coproc git commit'
# An escaped separator is word content. Neutralised in the masking pass rather
# than by asking the anchor for "a separator not preceded by a backslash" —
# that phrasing cannot count parity and re-opened k=5,9,13 as fail-opens.
run_row ""        inert "" 'echo \; git commit'
run_row ""        inert "" 'echo \& git commit'
run_row ""        inert "" 'echo \| git commit'
# HEREDOCS ARE NOT MASKED — see the reverted-pass note in the hook. A heredoc
# writing a script that contains the verb is blocked. It is a false POSITIVE and
# it fails CLOSED; the masker that fixed it introduced six fail-opens and is
# reverted. These rows pin the fail-closed behaviour so the revert cannot be
# undone silently, and Sol's six repros are pinned below as the reason.
hd="cat > script.sh <<'EOF'
git commit -m x
EOF"
truth=$(oracle "$hd"); g=$(gate "$hd")
if [ "$truth" = "inert" ] && [ "$g" = "BLOCK" ]; then
    pass "ACCEPTED LIMIT still holds (inert, blocked — heredoc body; masking it cost six fail-opens) — heredoc writing a script"
else
    fail "ACCEPTED LIMIT changed [oracle=$truth gate=$g] — heredoc writing a script"
fi

echo "--- Sol round 6: the SIX shapes the reverted heredoc masker let through ---"
# Every one of these invokes git, was ALLOWED by the awk masking pass, and is
# BLOCKED here. They are the evidence for the revert and must stay blocked.
#
# Sol's round 7 corrected this block twice, and both corrections are why it is
# worth having: the original `(( x = 1 << 2 ))` row did NOT demonstrate the
# defect — the reverted pass blocked it too, because `2` is not delimiter-like.
# `<< EOF` is the shape that actually escaped. And the count was six, not five:
# the expanding-body row was described in prose but never counted.
run_row ""        INVOKES "" '# documentation: use <<EOF below
git commit -m x'
# The exact single-quoted spelling, not just its double-quoted equivalent.
run_row ""        INVOKES "" 'echo '"'"'<<EOF'"'"'
git commit -m x'
run_row ""        INVOKES "" 'cat <<< EOF
git commit -m x'
run_row ""        INVOKES "" '(( x = 1 << EOF ))
git commit -m x'
# `<<-` with a TAB-indented terminator. At the masking stage the tab was still
# the escape `\t`, so `[[:space:]]*` never matched the terminator and the pass
# swallowed the real command after it. The tab below is literal and load-bearing.
run_row ""        INVOKES "" 'cat <<-EOF
body
	EOF
git commit -m x'
# An unquoted heredoc body is NOT inert: the substitution runs while the
# redirection is built. The reverted pass claimed otherwise.
# shellcheck disable=SC2016  # the substitution must reach the gate unexpanded —
# expanding it here would run the fixture's fake git instead of testing the text.
run_row ""        INVOKES "" 'cat <<EOF
$(git commit -m x)
EOF'

echo "--- GATE_WORD self-hunt: 25 shapes probed, these are the distinct ones ---"
# GATE_WORD is the load-bearing abstraction of this fix and it is used at all
# six sites that consume a word:
#
#   1. assignment values          4. the path prefix on `git`
#   2. redirection operands       5. git's own global-option operands
#   3. the wholesale skip         6. the path prefix on a WRAPPER
#
# so it got its own hunt. These are the structurally distinct survivors:
# loop and case bodies, a tab separator, an end-of-options marker, stacked
# wrappers, and an assignment/redirection/assignment interleave. None was a
# fail-open; they are pinned so a later change to GATE_WORD cannot quietly
# break one.
run_row ""        INVOKES "" 'for i in 1; do git commit -m x; done'
run_row ""        INVOKES "" 'case x in x) git commit -m x;; esac'
run_row ""        INVOKES "" 'env	git commit -m x'
run_row ""        INVOKES "" 'env -- git commit -m x'
run_row ""        INVOKES "" 'nohup env nice git commit -m x'
run_row ""        INVOKES "" 'env A=1 </dev/null B=2 git commit -m x'

echo "--- coproc (oracle: INVOKES, want BLOCK) ---"
# `coproc NAME { ...; }` blocks through the `{` anchor; bare `coproc git commit`
# blocks through the coproc keyword itself. Both need the oracle's trailing
# `wait` to be measurable at all — see the note on oracle().
run_row ""        INVOKES "" 'coproc git commit -m x'
run_row ""        INVOKES "" 'coproc G { git commit -m x; }'

echo "--- redirections inside the wrapper skip (Sol round 3, all fail-open) ---"
# The skip stopped at any `&`, so the `&` of a redirection operator ended it
# early and the invocation walked. Both of these run git.
run_row "env"     INVOKES "" 'env 2>&1 git commit -m x'
run_row "env"     INVOKES "" 'env &>/dev/null git commit -m x'

echo "--- escaped wrapper names and builtin (Sol round 3, all fail-open) ---"
# `\env` is the same escape rule the detector already applied to `git` but
# never to the wrapper. `builtin` was simply missing from the enumerated set.
run_row "env"     INVOKES "" '\env git commit -m x'
run_row "env"     INVOKES "" '/usr/bin/\env git commit -m x'
run_row ""        inert   "" 'builtin git commit -m x'
run_row ""        INVOKES "" 'builtin command git commit -m x'
run_row ""        INVOKES "" 'builtin exec git commit -m x'
run_row ""        INVOKES "" 'builtin eval git commit -m x'

echo "--- more redirection operand shapes (Sol round 3, these already held) ---"
run_row ""        INVOKES "" '> /dev/null git commit -m x'
run_row ""        INVOKES "" '<<< x git commit -m x'

# `coproc NAME cmd` is NOT the coprocess form: with a simple command bash takes
# the first word as the command, so `G` is run and git never is. Sol declared
# this INVOKES in round 3; the oracle says otherwise and the oracle is ground
# truth. Pinned so the disagreement is settled in the file rather than re-argued.
run_row ""        inert "" 'coproc G git commit -m x'

echo "--- prose and arguments (oracle: inert, want ALLOW) ---"
run_row ""        inert "" 'echo the git commit gate'
run_row ""        inert "" 'grep -rn git commit hooks/'
run_row ""        inert "" "grep -n 'git commit' hooks/codex-gate-check.sh"
run_row ""        inert "" 'grep -n "git commit" hooks/codex-gate-check.sh'
run_row ""        inert "" "gh pr comment 1 --body 'we ran git commit here'"
run_row ""        inert "" 'echo see docs/git commit-policy.md'

echo "--- #581 split shapes still block through the ; normalization ---"
# The upstream \n -> ';' rewrite is what keeps these caught once `git` must sit
# at command position: ';' is itself an anchor. Without that, anchoring would
# silently re-open #581.
run_row ""        INVOKES "" 'cd foo
git commit -m x'
run_row ""        inert   "" 'echo x
echo git commit'

echo "--- ACCEPTED LIMITS: rows that pin behaviour we know is wrong ---"
# A detector needs known-FAILURE rows, not only known-success ones. These assert
# the CURRENT, deliberately-accepted behaviour, so that a later change which
# either fixes or worsens one of them shows up as a diff rather than passing
# silently. Each is recorded on #588.
#
# Every row here is a false NEGATIVE — the shape really does invoke git and the
# gate allows it. That is the direction that matters, and it is why the wrapper
# set had to be enumerated at all rather than the anchor shipping bare.
limit_row() {
    local why="$1" cmd="$2" truth g
    truth=$(oracle "$cmd")
    g=$(gate "$cmd")
    if [ "$truth" = "INVOKES" ] && [ "$g" = "ALLOW" ]; then
        pass "ACCEPTED LIMIT still holds (invokes, allowed) — $why: $cmd"
    else
        fail "ACCEPTED LIMIT changed [oracle=$truth gate=$g] — $why: $cmd. If this was deliberate, update #588 and this row; if not, it is a regression."
    fi
}

# The FALSE POSITIVE bought by skipping wrapper option arguments wholesale. The
# text cannot say whether `echo` is `time`'s option argument or a new command
# word, so this inert shape is blocked. Asserted in the opposite direction from
# the other rows here — it is a false POSITIVE, so `limit_row` does not fit and
# it is checked inline.
tfp='time echo git commit'
truth=$(oracle "$tfp"); g=$(gate "$tfp")
if [ "$truth" = "inert" ] && [ "$g" = "BLOCK" ]; then
    pass "ACCEPTED LIMIT still holds (inert, blocked — the cost of the wholesale wrapper skip) — $tfp"
else
    fail "ACCEPTED LIMIT changed [oracle=$truth gate=$g] — $tfp"
fi

# A quoted payload handed to a shell or to eval. The masking pass collapses the
# quoted span to `Q` before any matching runs, so the verb is invisible to the
# detector. Measured against origin/main: ALLOWED there too, so this is NOT
# introduced by the command-position change — it predates it, and it is filed
# separately rather than fixed inside a PR about prose false-positives.
limit_row "quoted payload is masked before matching (pre-existing on origin/main)" "bash -c 'git commit -m x'"
limit_row "quoted payload is masked before matching (pre-existing on origin/main)" "eval 'git commit -m x'"
limit_row "quoted wrapper name is masked before matching (same #599 class)" '"/usr/bin/env" git commit -m x'

# NESTED SHELL SUBSTITUTIONS (Sol round 4). A separator inside ${...}, $(...),
# $((...)) or backticks is not an outer command boundary, but GATE_WORD stops
# there anyway. Substitutions nest arbitrarily, so no regex closes this — it is
# the same constraint as the quoted-payload rows above and #533's ruling against
# positive command parsing, and it is dispositioned the same way rather than
# chased. origin/main "blocks" these only because \bgit blocked every string
# containing the verb, prose included, which is the defect #588 exists to fix.
# shellcheck disable=SC2016  # (applies to all three rows) the single quotes are the POINT: these shapes
# must reach the gate as literal text, unexpanded, or the row stops testing the
# substitution syntax it names.
limit_row "separator inside a parameter expansion (nests arbitrarily; #599 class)" 'FOO=${UNSET:-a;b}x git commit -m x'
# shellcheck disable=SC2016
limit_row "separator inside an arithmetic expansion (nests arbitrarily; #599 class)" 'FOO=$((1|2))x git commit -m x'
# shellcheck disable=SC2016
limit_row "separator inside a command substitution (nests arbitrarily; #599 class)" 'FOO=$(printf a; :)x git commit -m x'

# A malformed redirection target. bash rejects `2>&notafd` and never reaches
# git, but the text is indistinguishable from a valid one. Fails CLOSED, and
# engineering around a shape that cannot run is not worth a grammar.
nfp='2>&notafd git commit -m x'
truth=$(oracle "$nfp"); g=$(gate "$nfp")
if [ "$truth" = "inert" ] && [ "$g" = "BLOCK" ]; then
    pass "ACCEPTED LIMIT still holds (inert, blocked — malformed redirection target) — $nfp"
else
    fail "ACCEPTED LIMIT changed [oracle=$truth gate=$g] — $nfp"
fi

# An un-enumerated wrapper. `caffeinate` is macOS-only, so the row is skipped
# where it does not exist rather than asserted vacuously.
if command -v caffeinate > /dev/null 2>&1; then
    limit_row "wrapper outside the closed set" 'caffeinate git commit -m x'
else
    echo "  SKIP: caffeinate absent — un-enumerated-wrapper row not measurable here"
fi

# A real commit into a throwaway repo outside the working tree. This is the
# second half of #588 and it is NOT fixed: deciding WHERE a command commits
# needs the cd-tracking that #533 ruled out. The gate blocks it today on text
# alone, so it is a false POSITIVE rather than a negative — asserted as such.
tmpfix="$WORK/throwaway"
mkdir -p "$tmpfix"
throwaway_cmd="cd $tmpfix && git commit -m x"
truth=$(oracle "$throwaway_cmd")
g=$(gate "$throwaway_cmd")
if [ "$truth" = "INVOKES" ] && [ "$g" = "BLOCK" ]; then
    pass "ACCEPTED LIMIT still holds (out-of-tree commit is a true positive by text, still blocked) — $throwaway_cmd"
else
    fail "ACCEPTED LIMIT changed [oracle=$truth gate=$g] — out-of-tree commit: $throwaway_cmd"
fi

echo "--- backslash runs k=1..16, oracle-derived (#581's contract, re-measured) ---"
# The shape is the JSON string `echo x<k backslashes>ngit commit -m y`. What the
# SHELL does with it depends on the PARITY of the decoded backslash run sitting
# in front of the newline: an even run leaves the newline real (a command
# separator, so git runs), an odd run makes it a line continuation (the words
# fuse and nothing is invoked).
#
# This is derived here, not asserted: the JSON is decoded to real shell text and
# fed to the same oracle as every other row.
#
# It matters because the old `\bgit` detector got the right answer on k=1,5,9,13
# for the WRONG REASON — a leftover literal backslash supplied the word boundary
# `\b` needed. Requiring command position removed that accident and exposed a
# real fail-OPEN in the normalization, which treated every run as a continuation
# regardless of parity. Fixing the parity also closed the k = 3 (mod 4) FALSE
# DENIALS that the hook previously declined as too costly to fix.
verb="com""mit"
for k in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16; do
    # shellcheck disable=SC1003  # '\\' is a literal backslash for tr, not an
    # attempt to escape a quote — building a run of k backslashes is the test.
    bs=$(printf '%*s' "$k" '' | tr ' ' '\\')
    json_cmd=$(printf 'echo x%sngit %s -m y' "$bs" "$verb")
    # Decode the JSON string escape to the real shell text the tool would run.
    shell_text=$(python3 -c 'import json,sys; print(json.loads("\"" + sys.argv[1] + "\""), end="")' "$json_cmd") || {
        fail "k=$k: could not decode the JSON command string"
        continue
    }
    truth=$(oracle "$shell_text")
    if [ "$truth" = "INVOKES" ]; then want=BLOCK; else want=ALLOW; fi

    json=$(printf '{"tool_name":"Bash","tool_input":{"command":"%s","description":"fixture"}}' "$json_cmd")
    if printf '%s' "$json" | ( cd "$WORK/clean" && ./hooks/codex-gate-check.sh ) > /dev/null 2>&1; then
        got=ALLOW
    else
        got=BLOCK
    fi

    if [ "$got" = "$want" ]; then
        pass "k=$k [oracle: $truth] gate $got"
    else
        fail "k=$k [oracle: $truth] gate $got, want $want"
    fi
done

echo
echo "=== $PASS passed, $FAIL failed ==="
[ "$FAIL" -eq 0 ]
