#!/bin/bash
# #588 — codex-gate must fire on git commit in COMMAND POSITION, and not on a
# command that merely mentions the verb.
#
# Why this suite exists separately from tests/test-hooks.sh: want values here are
# GENERATED BY AN ORACLE wherever the oracle can run, rather than hand-asserted.
# A bash oracle puts a fake `git` on PATH that logs whenever it is invoked with
# `commit`, runs the real shape through `bash -c`, and reports whether git was
# actually invoked. That is ground truth for what the shell does; the gate's job
# is to agree with it.
#
# FOUR ROWS ARE NOT ORACLE-GENERATED on this box, and saying otherwise would
# break this repo's own claim rule (Sol caught an earlier version of this
# comment doing exactly that). They are `declared`, and each prints its reason
# when it runs:
#
#   timeout 5s git commit    `timeout` is not installed on macOS
#   stdbuf -oL git commit    `stdbuf` is not installed on macOS
#   sudo git commit          sudo cannot run unattended in a fixture
#   /usr/bin/git commit      an absolute path bypasses the PATH interposition
#                            the oracle works by, so it is declared on EVERY
#                            platform, not just this one
#
# `timeout` and `stdbuf` are named by bare name, so they measure for real on any
# box that has them — including the Linux CI runner. `sudo` and `/usr/bin/git`
# carry the `!` marker and are declared on EVERY platform. Everything else in
# the suite is measured here.
#
# This method is not decoration. The first hand-written want column for these
# shapes had 2 of 9 rows wrong, and BOTH errors under-counted the regression:
#
#   - `timeout 5 git commit` looked inert only because `timeout` is not
#     installed on macOS. It exists on the Linux CI runner and on consumer
#     machines.
#   - `xargs git commit < /dev/null` looked inert only because BSD xargs does
#     not run the command on empty input. GNU xargs does, and consumers run
#     Linux.
#
# Both are handled below rather than papered over: a shape whose wrapper is
# absent on this box is reported ORACLE-UNAVAILABLE and asserted against a
# declared expectation with its reason, so the row never silently degrades into
# a vacuous pass.
#
# The gate is an accident-catcher, not an adversary barrier — its own header
# says so, and #588 concedes deliberate bypass is trivial. So the wrapper set is
# CLOSED and enumerated. Wrappers outside it (doas, setsid, caffeinate,
# unbuffer, flock, ...) are a known, accepted false NEGATIVE, recorded on #588.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"


PASS=0
FAIL=0
pass() { echo "  PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); }

WORK=$(mktemp -d) || { echo "FATAL: could not create temp dir" >&2; exit 1; }
case "$WORK" in
    /*) ;;
    *) echo "FATAL: mktemp returned a non-absolute path ('$WORK') — refusing to run" >&2; exit 1 ;;
esac
trap 'rm -rf "$WORK"' EXIT

# ---------------------------------------------------------------- the oracle
#
# A fake `git` that records an invocation when ANY argument is exactly `commit`
# — it does not parse the subcommand chain, and claiming it did would break this
# repo's own claim rule. That is deliberately coarse: this oracle answers "did
# the shell run git with the verb in its argv", which is the question the gate
# is deciding, not "what would git have done". It never touches a real
# repository, so a row that genuinely invokes git cannot create a commit.
mkdir -p "$WORK/bin"
cat > "$WORK/bin/git" <<'ORACLE_GIT'
#!/bin/bash
for a in "$@"; do
    if [ "$a" = "commit" ]; then
        echo INVOKED >> "$ORACLE_LOG"
        exit 0
    fi
done
exit 0
ORACLE_GIT
chmod +x "$WORK/bin/git"

# Runs a shape and reports what the SHELL does with it: INVOKES or inert.
oracle() {
    ORACLE_LOG="$WORK/oracle.log"
    export ORACLE_LOG
    : > "$ORACLE_LOG"
    # The trailing `wait` is load-bearing for backgrounding shapes: `coproc git
    # commit` genuinely invokes, but the coprocess runs asynchronously and
    # `bash -c` exits before it writes the log. Without the wait the oracle
    # reports `inert` for a shape that really runs git — a false ALLOW want.
    ( cd "$WORK" && PATH="$WORK/bin:$PATH" bash -c "$1"$'\n''wait' ) > /dev/null 2>&1
    if [ -s "$ORACLE_LOG" ]; then echo INVOKES; else echo inert; fi
}

# Runs a shape through the gate's TEXT layer only, on a root with no
# .reviews/handoff.json. Probing inside the working repo is confounded: the
# in-flight PENDING_RECHECK lane allows real commits, so `git commit -m x`
# reports ALLOW there for reasons that have nothing to do with #588.
mkdir -p "$WORK/clean/hooks"
cp "$REPO_ROOT/hooks/codex-gate-check.sh" "$REPO_ROOT/hooks/_find-sdlc-root.sh" "$WORK/clean/hooks/"
gate() {
    local json
    json=$(python3 -c 'import json,sys; print(json.dumps({"tool_name":"Bash","tool_input":{"command":sys.argv[1],"description":"fixture"}}))' "$1")
    if printf '%s' "$json" | ( cd "$WORK/clean" && ./hooks/codex-gate-check.sh ) > /dev/null 2>&1; then
        echo ALLOW
    else
        echo BLOCK
    fi
}

# Fixture state the rows depend on. Without these the oracle reports `inert` for
# a shape that genuinely invokes — a false PASS waiting to happen, and exactly
# what the oracle/declared cross-check below is here to catch.
mkdir -p "$WORK/sub"          # so `cd sub && ...` does not short-circuit on &&
cp "$WORK/bin/git" "$WORK/git" # so `./git commit` resolves to the fake

# A row the oracle cannot measure here. Two causes, both real:
#   - the named wrapper is not installed on this box
#   - the shape names an ABSOLUTE path to git, which by construction bypasses
#     the PATH interposition the oracle works by
# Either way the row falls back to its declared value WITH its reason printed,
# so an unmeasurable row can never quietly read as `inert`.
oracle_can_measure() {
    case "$1" in
        "")  return 0 ;;
        "!"*) return 1 ;;
        *)   command -v "$1" > /dev/null 2>&1 ;;
    esac
}

# ------------------------------------------------------------------ the table
#
# Fields: wrapper-binary-needed | declared | reason | command
#   declared      what the shape does in a POSIX shell where every named binary
#                 exists. Used ONLY when the oracle cannot run here.
# The oracle overrides `declared` whenever it can run. A disagreement between
# the two is itself reported, because it means one of them is wrong.
run_row() {
    local needs="$1" declared="$2" reason="$3" cmd="$4"
    local truth source g want

    if oracle_can_measure "$needs"; then
        truth=$(oracle "$cmd")
        source="oracle"
        if [ "$truth" != "$declared" ]; then
            fail "oracle/declared disagree for [$cmd]: oracle says $truth, table declares $declared — one of them is wrong"
            return
        fi
    else
        truth="$declared"
        source="declared (${needs#!} unmeasurable here: $reason)"
    fi

    if [ "$truth" = "INVOKES" ]; then want=BLOCK; else want=ALLOW; fi
    g=$(gate "$cmd")

    if [ "$g" = "$want" ]; then
        pass "[$source: $truth] gate $g — $cmd"
    else
        fail "[$source: $truth] gate $g, want $want — $cmd"
    fi
}

echo "=== #588: gate agrees with the shell about what invokes git commit ==="

echo "--- real invocations (oracle: INVOKES, want BLOCK) ---"
run_row ""        INVOKES "" 'git commit -m x'
run_row ""        INVOKES "" 'cd sub && git commit -m x'
run_row ""        INVOKES "" '(cd sub; git commit -m x)'
run_row ""        INVOKES "" 'git -C /tmp/r commit -m x'
run_row ""        INVOKES "" 'git -c user.name="A B" commit -m x'

echo "--- enumerated wrapper prefixes (oracle: INVOKES, want BLOCK) ---"
run_row "env"     INVOKES "" 'env X=1 git commit -m x'
run_row "command" INVOKES "" 'command git commit -m x'
run_row "nice"    INVOKES "" 'nice git commit -m x'
run_row "nohup"   INVOKES "" 'nohup git commit -m x'
# WITH input, deliberately. `xargs git commit < /dev/null` invokes on GNU and
# not on BSD; the fed form invokes on both, so the row means the same thing on
# the dev box and the CI runner.
run_row "xargs"   INVOKES "" 'echo -m x | xargs git commit'
run_row "timeout" INVOKES "not installed on macOS; present on the Linux runner and on consumer machines" 'timeout 5 git commit -m x'

echo "--- eval/exec/time and escaped git (oracle: INVOKES, want BLOCK) ---"
# Every row here was found by hunting fail-opens with the oracle BEFORE review,
# and every one shipped blocked on origin/main. Anchoring alone would have let
# them through — the regression these rows exist to prevent.
run_row ""        INVOKES "" 'eval git commit -m x'
run_row ""        INVOKES "" 'exec git commit -m x'
run_row ""        INVOKES "" 'time git commit -m x'
# `\git` runs git — the escape only suppresses alias expansion.
run_row ""        INVOKES "" '\git commit -m x'
# `builtin` is deliberately NOT transparent: it only runs shell builtins, and
# git is not one, so the shape is inert and allowing it is correct. origin/main
# denied it; that false positive is fixed here.
run_row ""        inert   "" 'builtin git commit -m x'

echo "--- reserved words and redirections (Sol round 1, all fail-open) ---"
# Every row here shipped BLOCKED on origin/main and walked past the first cut of
# the command-position anchor. bash begins a command after these reserved words
# exactly as it does after then/do/else, and it permits redirections before the
# command word.
run_row ""        INVOKES "" 'if git commit -m x; then :; fi'
run_row ""        INVOKES "" 'while git commit -m x; do break; done'
run_row ""        INVOKES "" 'until git commit -m x; do break; done'
run_row ""        INVOKES "" '</dev/null git commit -m x'
run_row ""        INVOKES "" '2>/dev/null git commit -m x'
run_row ""        INVOKES "" 'FOO=1 </dev/null git commit -m x'

echo "--- wrapper options that take an argument (Sol round 1, all fail-open) ---"
# The first cut allowed only flags and bare numbers after a wrapper, so an
# option with an argument broke the chain. Enumerating each wrapper's real
# option grammar is not winnable, so the tokens between an enumerated wrapper
# and `git` are skipped wholesale, stopping at `;`, `&` or `|`.
run_row "env"     INVOKES "" 'env -u FOO git commit -m x'
run_row "xargs"   INVOKES "" "printf 'x\n' | xargs -I X git commit -m X"
run_row "timeout" INVOKES "not installed on macOS; present on the Linux runner and on consumer machines" 'timeout 5s git commit -m x'

echo "--- assignment prefixes (oracle: INVOKES, want BLOCK) ---"
# bash runs an assignment-prefixed command directly — there is no wrapper here
# at all. This repo's own workflow uses the shape (AFTERHOURS_SKIP=1 git push).
run_row ""        INVOKES "" 'FOO=1 git commit -m x'
run_row ""        INVOKES "" 'GIT_AUTHOR_NAME="A B" git commit -m x'

echo "--- path-prefixed git (oracle: INVOKES, want BLOCK) ---"
run_row "!absolute path" INVOKES "an absolute path bypasses the PATH interposition the oracle works by" '/usr/bin/git commit -m x'
run_row ""        INVOKES "" './git commit -m x'

echo "--- path-prefixed WRAPPERS (oracle: INVOKES, want BLOCK) ---"
# The `(\S*/)?` prefix went on `git` in the first cut but not on the wrapper
# alternation, so a wrapper named by path escaped while its bare name was
# caught. `/usr/bin/env` is a shape people type without thinking about it.
run_row ""        INVOKES "" '/usr/bin/env git commit -m x'
run_row ""        INVOKES "" '/usr/bin/nice git commit -m x'
run_row ""        INVOKES "" '/usr/bin/env -u FOO git commit -m x'

echo "--- backslash-escaped word content (Sol round 2, all fail-open) ---"
# A backslash makes the next character ordinary word content. Modelling a word
# as "runs to the next space or separator" splits each of these early and lets
# the invocation through. All four block on origin/main.
run_row ""        INVOKES "" 'FOO=a\ b git commit -m x'
run_row ""        INVOKES "" 'env FOO=a\;b git commit -m x'
run_row ""        INVOKES "" 'env FOO=a\&b git commit -m x'
run_row ""        INVOKES "" 'env FOO=a\|b git commit -m x'

echo "--- redirection operand separated from its operator (Sol round 2) ---"
# `< /dev/null git commit` is an ordinary invocation; the space after the
# operator is legal and GATE_REDIR used to require the operand to touch it.
run_row ""        INVOKES "" '< /dev/null git commit -m x'
run_row ""        INVOKES "" '2> /dev/null git commit -m x'

echo "--- remaining enumerated wrappers and reserved words, pinned (Sol round 2) ---"
# Named in the hook's comment as covered, so they are pinned here rather than
# left as an untested claim. sudo is unmeasurable: it prompts or refuses.
run_row "!sudo"   INVOKES "sudo cannot run unattended in a test fixture" 'sudo git commit -m x'
run_row "stdbuf"  INVOKES "not installed on macOS; present on the Linux runner" 'stdbuf -oL git commit -m x'
run_row ""        INVOKES "" 'if false; then :; elif git commit -m x; then :; fi'

echo "--- GATE_WORD self-hunt: 25 shapes probed, these are the distinct ones ---"
# GATE_WORD is the load-bearing abstraction of this fix and it is used at four
# sites, so it got its own hunt. These are the structurally distinct survivors:
# loop and case bodies, a tab separator, an end-of-options marker, stacked
# wrappers, and an assignment/redirection/assignment interleave. None was a
# fail-open; they are pinned so a later change to GATE_WORD cannot quietly
# break one.
run_row ""        INVOKES "" 'for i in 1; do git commit -m x; done'
run_row ""        INVOKES "" 'case x in x) git commit -m x;; esac'
run_row ""        INVOKES "" 'env	git commit -m x'
run_row ""        INVOKES "" 'env -- git commit -m x'
run_row ""        INVOKES "" 'nohup env nice git commit -m x'
run_row ""        INVOKES "" 'env A=1 </dev/null B=2 git commit -m x'

echo "--- coproc (oracle: INVOKES, want BLOCK) ---"
# `coproc NAME { ...; }` blocks through the `{` anchor; bare `coproc git commit`
# blocks through the coproc keyword itself. Both need the oracle's trailing
# `wait` to be measurable at all — see the note on oracle().
run_row ""        INVOKES "" 'coproc git commit -m x'
run_row ""        INVOKES "" 'coproc G { git commit -m x; }'

echo "--- redirections inside the wrapper skip (Sol round 3, all fail-open) ---"
# The skip stopped at any `&`, so the `&` of a redirection operator ended it
# early and the invocation walked. Both of these run git.
run_row "env"     INVOKES "" 'env 2>&1 git commit -m x'
run_row "env"     INVOKES "" 'env &>/dev/null git commit -m x'

echo "--- escaped wrapper names and builtin (Sol round 3, all fail-open) ---"
# `\env` is the same escape rule the detector already applied to `git` but
# never to the wrapper. `builtin` was simply missing from the enumerated set.
run_row "env"     INVOKES "" '\env git commit -m x'
run_row "env"     INVOKES "" '/usr/bin/\env git commit -m x'
run_row ""        inert   "" 'builtin git commit -m x'
run_row ""        INVOKES "" 'builtin command git commit -m x'
run_row ""        INVOKES "" 'builtin exec git commit -m x'
run_row ""        INVOKES "" 'builtin eval git commit -m x'

echo "--- more redirection operand shapes (Sol round 3, these already held) ---"
run_row ""        INVOKES "" '> /dev/null git commit -m x'
run_row ""        INVOKES "" '<<< x git commit -m x'

# `coproc NAME cmd` is NOT the coprocess form: with a simple command bash takes
# the first word as the command, so `G` is run and git never is. Sol declared
# this INVOKES in round 3; the oracle says otherwise and the oracle is ground
# truth. Pinned so the disagreement is settled in the file rather than re-argued.
run_row ""        inert "" 'coproc G git commit -m x'

echo "--- prose and arguments (oracle: inert, want ALLOW) ---"
run_row ""        inert "" 'echo the git commit gate'
run_row ""        inert "" 'grep -rn git commit hooks/'
run_row ""        inert "" "grep -n 'git commit' hooks/codex-gate-check.sh"
run_row ""        inert "" 'grep -n "git commit" hooks/codex-gate-check.sh'
run_row ""        inert "" "gh pr comment 1 --body 'we ran git commit here'"
run_row ""        inert "" 'echo see docs/git commit-policy.md'

echo "--- #581 split shapes still block through the ; normalization ---"
# The upstream \n -> ';' rewrite is what keeps these caught once `git` must sit
# at command position: ';' is itself an anchor. Without that, anchoring would
# silently re-open #581.
run_row ""        INVOKES "" 'cd foo
git commit -m x'
run_row ""        inert   "" 'echo x
echo git commit'

echo "--- ACCEPTED LIMITS: rows that pin behaviour we know is wrong ---"
# A detector needs known-FAILURE rows, not only known-success ones. These assert
# the CURRENT, deliberately-accepted behaviour, so that a later change which
# either fixes or worsens one of them shows up as a diff rather than passing
# silently. Each is recorded on #588.
#
# Every row here is a false NEGATIVE — the shape really does invoke git and the
# gate allows it. That is the direction that matters, and it is why the wrapper
# set had to be enumerated at all rather than the anchor shipping bare.
limit_row() {
    local why="$1" cmd="$2" truth g
    truth=$(oracle "$cmd")
    g=$(gate "$cmd")
    if [ "$truth" = "INVOKES" ] && [ "$g" = "ALLOW" ]; then
        pass "ACCEPTED LIMIT still holds (invokes, allowed) — $why: $cmd"
    else
        fail "ACCEPTED LIMIT changed [oracle=$truth gate=$g] — $why: $cmd. If this was deliberate, update #588 and this row; if not, it is a regression."
    fi
}

# The FALSE POSITIVE bought by skipping wrapper option arguments wholesale. The
# text cannot say whether `echo` is `time`'s option argument or a new command
# word, so this inert shape is blocked. Asserted in the opposite direction from
# the other rows here — it is a false POSITIVE, so `limit_row` does not fit and
# it is checked inline.
tfp='time echo git commit'
truth=$(oracle "$tfp"); g=$(gate "$tfp")
if [ "$truth" = "inert" ] && [ "$g" = "BLOCK" ]; then
    pass "ACCEPTED LIMIT still holds (inert, blocked — the cost of the wholesale wrapper skip) — $tfp"
else
    fail "ACCEPTED LIMIT changed [oracle=$truth gate=$g] — $tfp"
fi

# A quoted payload handed to a shell or to eval. The masking pass collapses the
# quoted span to `Q` before any matching runs, so the verb is invisible to the
# detector. Measured against origin/main: ALLOWED there too, so this is NOT
# introduced by the command-position change — it predates it, and it is filed
# separately rather than fixed inside a PR about prose false-positives.
limit_row "quoted payload is masked before matching (pre-existing on origin/main)" "bash -c 'git commit -m x'"
limit_row "quoted payload is masked before matching (pre-existing on origin/main)" "eval 'git commit -m x'"

# An un-enumerated wrapper. `caffeinate` is macOS-only, so the row is skipped
# where it does not exist rather than asserted vacuously.
if command -v caffeinate > /dev/null 2>&1; then
    limit_row "wrapper outside the closed set" 'caffeinate git commit -m x'
else
    echo "  SKIP: caffeinate absent — un-enumerated-wrapper row not measurable here"
fi

# A real commit into a throwaway repo outside the working tree. This is the
# second half of #588 and it is NOT fixed: deciding WHERE a command commits
# needs the cd-tracking that #533 ruled out. The gate blocks it today on text
# alone, so it is a false POSITIVE rather than a negative — asserted as such.
tmpfix="$WORK/throwaway"
mkdir -p "$tmpfix"
throwaway_cmd="cd $tmpfix && git commit -m x"
truth=$(oracle "$throwaway_cmd")
g=$(gate "$throwaway_cmd")
if [ "$truth" = "INVOKES" ] && [ "$g" = "BLOCK" ]; then
    pass "ACCEPTED LIMIT still holds (out-of-tree commit is a true positive by text, still blocked) — $throwaway_cmd"
else
    fail "ACCEPTED LIMIT changed [oracle=$truth gate=$g] — out-of-tree commit: $throwaway_cmd"
fi

echo "--- backslash runs k=1..16, oracle-derived (#581's contract, re-measured) ---"
# The shape is the JSON string `echo x<k backslashes>ngit commit -m y`. What the
# SHELL does with it depends on the PARITY of the decoded backslash run sitting
# in front of the newline: an even run leaves the newline real (a command
# separator, so git runs), an odd run makes it a line continuation (the words
# fuse and nothing is invoked).
#
# This is derived here, not asserted: the JSON is decoded to real shell text and
# fed to the same oracle as every other row.
#
# It matters because the old `\bgit` detector got the right answer on k=1,5,9,13
# for the WRONG REASON — a leftover literal backslash supplied the word boundary
# `\b` needed. Requiring command position removed that accident and exposed a
# real fail-OPEN in the normalization, which treated every run as a continuation
# regardless of parity. Fixing the parity also closed the k = 3 (mod 4) FALSE
# DENIALS that the hook previously declined as too costly to fix.
verb="com""mit"
for k in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16; do
    bs=$(printf '%*s' "$k" '' | tr ' ' '\\')
    json_cmd=$(printf 'echo x%sngit %s -m y' "$bs" "$verb")
    # Decode the JSON string escape to the real shell text the tool would run.
    shell_text=$(python3 -c 'import json,sys; print(json.loads("\"" + sys.argv[1] + "\""), end="")' "$json_cmd") || {
        fail "k=$k: could not decode the JSON command string"
        continue
    }
    truth=$(oracle "$shell_text")
    if [ "$truth" = "INVOKES" ]; then want=BLOCK; else want=ALLOW; fi

    json=$(printf '{"tool_name":"Bash","tool_input":{"command":"%s","description":"fixture"}}' "$json_cmd")
    if printf '%s' "$json" | ( cd "$WORK/clean" && ./hooks/codex-gate-check.sh ) > /dev/null 2>&1; then
        got=ALLOW
    else
        got=BLOCK
    fi

    if [ "$got" = "$want" ]; then
        pass "k=$k [oracle: $truth] gate $got"
    else
        fail "k=$k [oracle: $truth] gate $got, want $want"
    fi
done

echo
echo "=== $PASS passed, $FAIL failed ==="
[ "$FAIL" -eq 0 ]
