#!/bin/bash
# #588 — codex-gate must fire on git commit in COMMAND POSITION, and not on a
# command that merely mentions the verb.
#
# Why this suite exists separately from tests/test-hooks.sh: every want value
# here is GENERATED BY AN ORACLE, not hand-asserted. A bash oracle puts a fake
# `git` on PATH that logs whenever it is invoked with `commit`, runs the real
# shape through `bash -c`, and reports whether git was actually invoked. That
# is ground truth for what the shell does; the gate's job is to agree with it.
#
# This method is not decoration. The first hand-written want column for these
# shapes had 2 of 9 rows wrong, and BOTH errors under-counted the regression:
#
#   - `timeout 5 git commit` looked inert only because `timeout` is not
#     installed on macOS. It exists on the Linux CI runner and on consumer
#     machines.
#   - `xargs git commit < /dev/null` looked inert only because BSD xargs does
#     not run the command on empty input. GNU xargs does, and consumers run
#     Linux.
#
# Both are handled below rather than papered over: a shape whose wrapper is
# absent on this box is reported ORACLE-UNAVAILABLE and asserted against a
# declared expectation with its reason, so the row never silently degrades into
# a vacuous pass.
#
# The gate is an accident-catcher, not an adversary barrier — its own header
# says so, and #588 concedes deliberate bypass is trivial. So the wrapper set is
# CLOSED and enumerated. Wrappers outside it (doas, setsid, caffeinate,
# unbuffer, flock, ...) are a known, accepted false NEGATIVE, recorded on #588.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"


PASS=0
FAIL=0
pass() { echo "  PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); }

WORK=$(mktemp -d) || { echo "FATAL: could not create temp dir" >&2; exit 1; }
case "$WORK" in
    /*) ;;
    *) echo "FATAL: mktemp returned a non-absolute path ('$WORK') — refusing to run" >&2; exit 1 ;;
esac
trap 'rm -rf "$WORK"' EXIT

# ---------------------------------------------------------------- the oracle
#
# A fake `git` that records an invocation whose first non-flag argument chain
# reaches the `commit` subcommand. It never touches a real repository, so a row
# that genuinely invokes git cannot create a commit anywhere.
mkdir -p "$WORK/bin"
cat > "$WORK/bin/git" <<'ORACLE_GIT'
#!/bin/bash
for a in "$@"; do
    if [ "$a" = "commit" ]; then
        echo INVOKED >> "$ORACLE_LOG"
        exit 0
    fi
done
exit 0
ORACLE_GIT
chmod +x "$WORK/bin/git"

# Runs a shape and reports what the SHELL does with it: INVOKES or inert.
oracle() {
    ORACLE_LOG="$WORK/oracle.log"
    export ORACLE_LOG
    : > "$ORACLE_LOG"
    ( cd "$WORK" && PATH="$WORK/bin:$PATH" bash -c "$1" ) > /dev/null 2>&1
    if [ -s "$ORACLE_LOG" ]; then echo INVOKES; else echo inert; fi
}

# Runs a shape through the gate's TEXT layer only, on a root with no
# .reviews/handoff.json. Probing inside the working repo is confounded: the
# in-flight PENDING_RECHECK lane allows real commits, so `git commit -m x`
# reports ALLOW there for reasons that have nothing to do with #588.
mkdir -p "$WORK/clean/hooks"
cp "$REPO_ROOT/hooks/codex-gate-check.sh" "$REPO_ROOT/hooks/_find-sdlc-root.sh" "$WORK/clean/hooks/"
gate() {
    local json
    json=$(python3 -c 'import json,sys; print(json.dumps({"tool_name":"Bash","tool_input":{"command":sys.argv[1],"description":"fixture"}}))' "$1")
    if printf '%s' "$json" | ( cd "$WORK/clean" && ./hooks/codex-gate-check.sh ) > /dev/null 2>&1; then
        echo ALLOW
    else
        echo BLOCK
    fi
}

# Fixture state the rows depend on. Without these the oracle reports `inert` for
# a shape that genuinely invokes — a false PASS waiting to happen, and exactly
# what the oracle/declared cross-check below is here to catch.
mkdir -p "$WORK/sub"          # so `cd sub && ...` does not short-circuit on &&
cp "$WORK/bin/git" "$WORK/git" # so `./git commit` resolves to the fake

# A row the oracle cannot measure here. Two causes, both real:
#   - the named wrapper is not installed on this box
#   - the shape names an ABSOLUTE path to git, which by construction bypasses
#     the PATH interposition the oracle works by
# Either way the row falls back to its declared value WITH its reason printed,
# so an unmeasurable row can never quietly read as `inert`.
oracle_can_measure() {
    case "$1" in
        "")  return 0 ;;
        "!"*) return 1 ;;
        *)   command -v "$1" > /dev/null 2>&1 ;;
    esac
}

# ------------------------------------------------------------------ the table
#
# Fields: wrapper-binary-needed | declared | reason | command
#   declared      what the shape does in a POSIX shell where every named binary
#                 exists. Used ONLY when the oracle cannot run here.
# The oracle overrides `declared` whenever it can run. A disagreement between
# the two is itself reported, because it means one of them is wrong.
run_row() {
    local needs="$1" declared="$2" reason="$3" cmd="$4"
    local truth source g want

    if oracle_can_measure "$needs"; then
        truth=$(oracle "$cmd")
        source="oracle"
        if [ "$truth" != "$declared" ]; then
            fail "oracle/declared disagree for [$cmd]: oracle says $truth, table declares $declared — one of them is wrong"
            return
        fi
    else
        truth="$declared"
        source="declared (${needs#!} unmeasurable here: $reason)"
    fi

    if [ "$truth" = "INVOKES" ]; then want=BLOCK; else want=ALLOW; fi
    g=$(gate "$cmd")

    if [ "$g" = "$want" ]; then
        pass "[$source: $truth] gate $g — $cmd"
    else
        fail "[$source: $truth] gate $g, want $want — $cmd"
    fi
}

echo "=== #588: gate agrees with the shell about what invokes git commit ==="

echo "--- real invocations (oracle: INVOKES, want BLOCK) ---"
run_row ""        INVOKES "" 'git commit -m x'
run_row ""        INVOKES "" 'cd sub && git commit -m x'
run_row ""        INVOKES "" '(cd sub; git commit -m x)'
run_row ""        INVOKES "" 'git -C /tmp/r commit -m x'
run_row ""        INVOKES "" 'git -c user.name="A B" commit -m x'

echo "--- enumerated wrapper prefixes (oracle: INVOKES, want BLOCK) ---"
run_row "env"     INVOKES "" 'env X=1 git commit -m x'
run_row "command" INVOKES "" 'command git commit -m x'
run_row "nice"    INVOKES "" 'nice git commit -m x'
run_row "nohup"   INVOKES "" 'nohup git commit -m x'
# WITH input, deliberately. `xargs git commit < /dev/null` invokes on GNU and
# not on BSD; the fed form invokes on both, so the row means the same thing on
# the dev box and the CI runner.
run_row "xargs"   INVOKES "" 'echo -m x | xargs git commit'
run_row "timeout" INVOKES "not installed on macOS; present on the Linux runner and on consumer machines" 'timeout 5 git commit -m x'

echo "--- assignment prefixes (oracle: INVOKES, want BLOCK) ---"
# bash runs an assignment-prefixed command directly — there is no wrapper here
# at all. This repo's own workflow uses the shape (AFTERHOURS_SKIP=1 git push).
run_row ""        INVOKES "" 'FOO=1 git commit -m x'
run_row ""        INVOKES "" 'GIT_AUTHOR_NAME="A B" git commit -m x'

echo "--- path-prefixed git (oracle: INVOKES, want BLOCK) ---"
run_row "!absolute path" INVOKES "an absolute path bypasses the PATH interposition the oracle works by" '/usr/bin/git commit -m x'
run_row ""        INVOKES "" './git commit -m x'

echo "--- prose and arguments (oracle: inert, want ALLOW) ---"
run_row ""        inert "" 'echo the git commit gate'
run_row ""        inert "" 'grep -rn git commit hooks/'
run_row ""        inert "" "grep -n 'git commit' hooks/codex-gate-check.sh"
run_row ""        inert "" 'grep -n "git commit" hooks/codex-gate-check.sh'
run_row ""        inert "" "gh pr comment 1 --body 'we ran git commit here'"
run_row ""        inert "" 'echo see docs/git commit-policy.md'

echo "--- #581 split shapes still block through the ; normalization ---"
# The upstream \n -> ';' rewrite is what keeps these caught once `git` must sit
# at command position: ';' is itself an anchor. Without that, anchoring would
# silently re-open #581.
run_row ""        INVOKES "" 'cd foo
git commit -m x'
run_row ""        inert   "" 'echo x
echo git commit'

echo "--- backslash runs k=1..16, oracle-derived (#581's contract, re-measured) ---"
# The shape is the JSON string `echo x<k backslashes>ngit commit -m y`. What the
# SHELL does with it depends on the PARITY of the decoded backslash run sitting
# in front of the newline: an even run leaves the newline real (a command
# separator, so git runs), an odd run makes it a line continuation (the words
# fuse and nothing is invoked).
#
# This is derived here, not asserted: the JSON is decoded to real shell text and
# fed to the same oracle as every other row.
#
# It matters because the old `\bgit` detector got the right answer on k=1,5,9,13
# for the WRONG REASON — a leftover literal backslash supplied the word boundary
# `\b` needed. Requiring command position removed that accident and exposed a
# real fail-OPEN in the normalization, which treated every run as a continuation
# regardless of parity. Fixing the parity also closed the k = 3 (mod 4) FALSE
# DENIALS that the hook previously declined as too costly to fix.
verb="com""mit"
for k in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16; do
    bs=$(printf '%*s' "$k" '' | tr ' ' '\\')
    json_cmd=$(printf 'echo x%sngit %s -m y' "$bs" "$verb")
    # Decode the JSON string escape to the real shell text the tool would run.
    shell_text=$(python3 -c 'import json,sys; print(json.loads("\"" + sys.argv[1] + "\""), end="")' "$json_cmd") || {
        fail "k=$k: could not decode the JSON command string"
        continue
    }
    truth=$(oracle "$shell_text")
    if [ "$truth" = "INVOKES" ]; then want=BLOCK; else want=ALLOW; fi

    json=$(printf '{"tool_name":"Bash","tool_input":{"command":"%s","description":"fixture"}}' "$json_cmd")
    if printf '%s' "$json" | ( cd "$WORK/clean" && ./hooks/codex-gate-check.sh ) > /dev/null 2>&1; then
        got=ALLOW
    else
        got=BLOCK
    fi

    if [ "$got" = "$want" ]; then
        pass "k=$k [oracle: $truth] gate $got"
    else
        fail "k=$k [oracle: $truth] gate $got, want $want"
    fi
done

echo
echo "=== $PASS passed, $FAIL failed ==="
[ "$FAIL" -eq 0 ]
